### ISSUE TITLE
Switching back to admin

### ISSUE THREAD

**Issue by alpinevp** [kellenmace/wp-admin-switcher#1]
When switching from anywhere in admin to the public facing side and then back, it doesn't return me to the same page that I was on.  It always returns back to the dashboard, thus defeating the concept of quickly checking an edit as now I have to go back to pages and then the actual page I was editing.

Great idea but not quite ready for primetime.

**Comment by kellenmace** [comment]
The extension tries to send you to the link in the WP admin bar, which would send you back to the wp-admin edit screen that that page. If the admin bar is not there though, it has no way to know what the page you were editing previously was, to it just sends you to /wp-admin. If you want to go right back to the page you were on previously and don't want to activate the WP admin bar to display on the front end, I would recommend using your browser's back button instead.

**Comment by alpinevp** [comment]
Wow, this has to be a new record for a response.  Over 3 years to respond, on a plugin I don’t even remember ever using.  Thanks for the smile.
