### ISSUE TITLE
Add to firefox?

### ISSUE THREAD

**Issue by wormeyman** [kellenmace/wp-admin-switcher#3]
Now that firefox has their new extensions format is there any way that you could put this in the firefox store?

**Comment by wormeyman** [comment]
Any thoughts? Is this no longer supported? I love using this on Chrome!

**Comment by kellenmace** [comment]
The Chrome extension is still supported. I don't have plans to release a version of it for Firefox, since I only use Chrome personally. It's open source though, so please feel free to fork it and create a Firefox version, if you like.

**Comment by xenio** [comment]
@wormeyman you can change the manifest.json
https://github.com/kellenmace/wp-admin-switcher/blob/e49ef028eaf064a075a5fb6c0b0ec875f6555be8/manifest.json#L15

with
"scripts": ["service-worker.js"]
